site_name: RestPS
repo_url: https://github.com/jpsider/RestPS
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- RestPS Basics:
  - What is RestPS: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Public Functions:
  - Invoke-DeployRestPS: Invoke-DeployRestPS.md
  - Start-RestPSListener: Start-RestPSListener.md
  - Invoke-SSLIgnore: Invoke-SSLIgnore.md